title: Ruby/Numo::NArray
description: Numerical N-dimensional array class for Ruby, similar to numpy.ndarray.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
